version: '3.9'

volumes:
  ipython_history: {}

services:
  # ################################################################################
  # Database
  # ################################################################################
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -t 5 -U ${COMPOSE_PROJECT_NAME}-user || false"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=${COMPOSE_PROJECT_NAME}-dev
      - POSTGRES_USER=${COMPOSE_PROJECT_NAME}-user
      - POSTGRES_PASSWORD=manager

  # ################################################################################
  # Django Backend / API
  # ################################################################################
  web:
    build: .
    volumes:
      - ./:/workspace
      - ipython_history:/root/.ipython/profile_default
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    ports:
      - "8000:8000"
    command: python3 manage.py runserver_plus 0.0.0.0:8000 --reloader-type stat
    depends_on:
      postgres:
          condition: service_healthy
